/*
 * Gradient API
 *
 * No description provided (generated by Swagger Codegen https:/github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https:/github.com/swagger-api/swagger-codegen.git)
 */
package routes

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/go-chi/chi/v5"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter(router *chi.Mux) *chi.Mux {
	for _, route := range routes {
		router.Method(route.Method, route.Pattern, route.HandlerFunc)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/",
		Index,
	},

	Route{
		"GradientIdDelete",
		strings.ToUpper("Delete"),
		"/gradient/{id}",
		GradientIdDelete,
	},

	Route{
		"GradientIdGet",
		strings.ToUpper("Get"),
		"/gradient/{id}",
		GradientIdGet,
	},

	Route{
		"GradientPost",
		strings.ToUpper("Post"),
		"/gradient",
		GradientPost,
	},

	Route{
		"LoginPost",
		strings.ToUpper("Post"),
		"/login",
		LoginPost,
	},

	Route{
		"LogoutPost",
		strings.ToUpper("Post"),
		"/logout",
		LogoutGet,
	},

	Route{
		"RefreshPost",
		strings.ToUpper("Post"),
		"/refresh",
		RefreshPost,
	},

	Route{
		"RegisterPost",
		strings.ToUpper("Post"),
		"/register",
		RegisterPost,
	},

	Route{
		"RootGet",
		strings.ToUpper("Get"),
		"/",
		RootGet,
	},

	Route{
		"RootPost",
		strings.ToUpper("Post"),
		"/",
		RootPost,
	},

	Route{
		"UserUsernameGet",
		strings.ToUpper("Get"),
		"/user/{username}",
		UserUsernameGet,
	},
}
